title: Java Docs
description: Course materials for AP Computer Science
theme: just-the-docs

url: https://katerinanavab.github.io/javadocs

aux_links:
  "Instructor Site":
    - "https://coderina.dev"

logo: "logo-apcs.png"
favicon_ico: "logo-apcs.png"

back_to_top: true
back_to_top_text: "⬆️ BACK TO TOP"
